# This is a basic workflow to help you get started with Actions

name: Deploy on commit to master

on:
  push:
    branches: [ master ]

jobs:
  sftp-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo "hello" >> deployfile.txt

    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.4
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: 22
        SOURCE: deployfile.txt
        TARGET: ${{ secrets.REMOTE_TARGET }}
        # Arguments to pass to rsync
        ARGS: # optional, default is -rltgoDzvO
