# This is a basic workflow to help you get started with Actions

name: Deploy on commit to master

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create deployment tarball
      run: |
         echo "hello" > test.txt
         echo "openssh test" >> test.txt
         ping -c 5 ${{ secrets.REMOTE_HOST }}
#        tar -cvf bigdata-deploy.tar --exclude ".git*" *
#        echo "host: ${{ secrets.REMOTE_HOST }}" >> tmp.log
#        echo "username: ${{ secrets.REMOTE_USER }}" >> tmp.log
#        echo "key: ${{ secrets.SERVER_SSH_KEY }}" >> tmp.log
#        echo "target: ${{ secrets.REMOTE_TARGET }}" >> tmp.log
#        cat tmp.log

#    - name: ls -a via ssh
#      uses: fifsky/ssh-action@master
#      with:
#        command: |
#          ls -a 
#        host: ${{ secrets.REMOTE_HOST }}
#        user: ${{ secrets.REMOTE_USER }}
#        key: ${{ secrets.SERVER_SSH_KEY}}

#    - name: Copy single file to remote
#      uses: garygrossgarten/github-action-scp@release
#      with:
#        local: test.txt
#        remote: ${{ secrets.REMOTE_TARGET }}
#        host: ${{ secrets.REMOTE_HOST }}
#        username: ${{ secrets.REMOTE_USER }}
#        privateKey: ${{ secrets.SERVER_SSH_KEY }}


#    - name: Copy deployment to remote host
#      uses: appleboy/scp-action@master
#      with: 
#        host: ${{ secrets.REMOTE_HOST }}
#        username: ${{ secrets.REMOTE_USER }}
#        port: 22
#        key: ${{ secrets.SERVER_SSH_KEY }}
#        passphrase: 
#        source: bigdata-deploy.tar
#        target: ${{ secrets.REMOTE_TARGET }}
      
#    - name: ssh deploy
#      uses: easingthemes/ssh-deploy@v2.1.4
#      with:
#        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#        REMOTE_USER: ${{ secrets.REMOTE_USER }}
#        REMOTE_PORT: 22
#        SOURCE: deployfile.txt
#        TARGET: ${{ secrets.REMOTE_TARGET }}
#        # Arguments to pass to rsync
#        ARGS: # optional, default is -rltgoDzvO
